[package]
name = "starbase_console"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "Console reporting layer."
repository = "https://github.com/moonrepo/starbase"
rust-version = "1.80.0"

[dependencies]
starbase_styles = { version = "0.4.4", path = "../styles" }
inquire = { version = "0.7.5", optional = true }
iocraft = { workspace = true, optional = true }
miette = { workspace = true }
parking_lot = "0.12.3"
tracing = { workspace = true }
tokio = { workspace = true, optional = true }

[dev-dependencies]
starbase_console = { path = ".", features = ["prompts", "ui"] }

[features]
default = []
prompts = ["dep:inquire"]
ui = ["dep:iocraft", "dep:tokio"]
