[package]
name = "starbase_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
darling = "0.14.4"
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = { version = "1.0.109", features = ["full"] }

[features]
tracing = []
