// Interactive E2E tests for the activation flow, rendered from the three
// hooks a session needs: both functions, and the registration.
//
// The non-interactive suite in `hook_e2e_test.rs` covers what a script can
// reach. Everything a prompt drives is invisible there: prompt triggers never
// fire, elvish's `edit:` module does not exist, and nu's `pre_prompt` entries
// are never parsed. These tests drive the real shell through a pty instead.
//
// Each session runs the same steps, and reports state by running an external
// `sh` helper. Reading the environment from a child process keeps the checks
// identical across shells, and asserts the thing that actually matters: that
// activation exported the variable. The statements the stub commands print,
// and the statement that clobbers the variable, are generated by this crate,
// so the formatters are exercised through a real shell too.
//
// A test is skipped when its shell is not installed, unless the shell is
// listed in `STARBASE_REQUIRED_SHELLS`, matching the non-interactive suite.

#![cfg(unix)]

mod pty;

use pty::Pty;
use starbase_sandbox::{Sandbox, create_empty_sandbox};
use starbase_shell::{Hook, ShellType, Statement};

struct Case {
    shell: ShellType,
    bin: &'static str,
    args: fn(&str) -> Vec<String>,
    extension: &'static str,
    /// How the hook file is evaluated in the running session, the way that
    /// shell's consumers are told to source it. `None` when the shell sourced
    /// it at startup instead
    evaluate: Option<fn(&str) -> String>,
    /// Typed to tear the session down, which is a call in xonsh
    deactivate_call: &'static str,
    /// False for the POSIX shells, which have no prompt trigger and only
    /// activate when `cd` runs
    activates_on_prompt: bool,
    /// A line editor either needs terminal capabilities or hangs asking for
    /// them, so each shell says what it wants
    term: &'static str,
    /// True for nu, which cannot evaluate statements where the function runs,
    /// and stages them for the next prompt instead
    defers_statements: bool,
}

fn setup(case: &Case) -> (Sandbox, String) {
    let shell = case.shell.build();
    let sandbox = create_empty_sandbox();
    let root = sandbox.path().display().to_string();

    // Reading the variable from a child process works the same in every shell,
    // and proves the activation exported it
    sandbox.create_file(
        "report.sh",
        "printf '%s foo=%s\\n' \"$1\" \"${E2E_FOO:-unset}\"\n",
    );

    sandbox.create_file(
        "activate.txt",
        format!("{}\n", shell.format_env_set("E2E_FOO", "123")),
    );
    sandbox.create_file(
        "deactivate.txt",
        format!("{}\n", shell.format_env_unset("E2E_FOO")),
    );

    let hook = [
        shell
            .format_hook(Hook::Activate {
                command: format!("cat {root}/activate.txt"),
                function: "_starbase_activate".into(),
            })
            .unwrap(),
        shell
            .format_hook(Hook::Deactivate {
                command: format!("cat {root}/deactivate.txt"),
                function: "_starbase_deactivate".into(),
            })
            .unwrap(),
        shell
            .format_hook(Hook::OnContextChange {
                function: "_starbase_activate".into(),
            })
            .unwrap(),
    ]
    .join("\n\n");

    sandbox.create_file(format!("hook.{}", case.extension), &hook);

    // Reporting from inside the file proves the clobber landed, whichever
    // shell ran it
    sandbox.create_file(
        format!("clobber.{}", case.extension),
        format!(
            "{}\nsh {root}/report.sh CLOBBER\n",
            shell.format_env_set("E2E_FOO", "changed")
        ),
    );

    (sandbox, root)
}

/// Return the value from the last `<label> foo=<value>` line, so that the
/// echoed command line can never be mistaken for the report it produced.
fn reported(output: &str, label: &str) -> String {
    let prefix = format!("{label} foo=");

    output
        .lines()
        // A prompt is drawn on the same line as the output that follows it
        .filter_map(|line| {
            line.find(&prefix)
                .map(|index| &line[index + prefix.len()..])
        })
        .next_back()
        .unwrap_or_else(|| panic!("no `{prefix}` line in transcript:\n{output}"))
        .trim()
        .to_owned()
}

fn run_case(case: Case) {
    let (sandbox, root) = setup(&case);

    let args = (case.args)(&root);
    let args = args.iter().map(String::as_str).collect::<Vec<_>>();

    let Some(mut session) = Pty::spawn_with_term(case.bin, &args, case.term) else {
        return;
    };

    let report = |label: &str| format!("sh {root}/report.sh {label}");

    // Nothing can be typed until one round trip has completed, since a shell
    // that is still starting up drops whatever was typed
    session.wait_until_ready(&report("READY"), "READY foo=");

    // Sourcing alone activates in a shell with a prompt trigger, since the
    // next prompt fires before anything else can run
    if let Some(evaluate) = case.evaluate {
        session.send(&evaluate(&format!("{root}/hook.{}", case.extension)));
    }

    let output = session.sync(&report("S1"), "S1 foo=");
    let expected = if case.activates_on_prompt {
        "123"
    } else {
        "unset"
    };

    assert_eq!(reported(&output, "S1"), expected, "{}", case.shell);

    // Both triggers converge here, since a prompt follows the directory change
    session.send("cd /tmp");

    let output = session.sync(&report("S2"), "S2 foo=");

    assert_eq!(reported(&output, "S2"), "123", "{}", case.shell);

    // Clobbering reports as it goes, so that the value it left behind is
    // asserted before a prompt has had the chance to reapply anything
    let evaluate = case.evaluate.unwrap_or(|path| format!("source {path}"));

    session.send(&evaluate(&format!("{root}/clobber.{}", case.extension)));

    let output = session.sync(&report("S3"), "S3 foo=");

    assert_eq!(reported(&output, "CLOBBER"), "changed", "{}", case.shell);

    // A prompt trigger reapplies the activation over the clobbered value,
    // where a directory trigger leaves it alone until the next `cd`
    let expected = if case.activates_on_prompt {
        "123"
    } else {
        "changed"
    };

    assert_eq!(reported(&output, "S3"), expected, "{}", case.shell);

    // Deactivating reports on the same line, since the trigger stays
    // registered and the next prompt would activate over the top of it
    session.send(&format!("{} ; {}", case.deactivate_call, report("S4")));

    let output = session.sync(&report("S5"), "S5 foo=");
    let expected = if case.defers_statements {
        // Nu stages the statements for the next prompt rather than applying
        // them where the function ran
        "123"
    } else {
        "unset"
    };

    assert_eq!(reported(&output, "S4"), expected, "{}", case.shell);

    // Deactivating does not unregister anything, so a shell with a prompt
    // trigger activates again on the very next prompt
    let expected = match (case.activates_on_prompt, case.defers_statements) {
        (_, true) => "unset",
        (true, _) => "123",
        (false, _) => "unset",
    };

    assert_eq!(reported(&output, "S5"), expected, "{}", case.shell);

    // And a directory change activates every shell again, deactivated or not
    session.send("cd /");

    let output = session.sync(&report("S6"), "S6 foo=");

    assert_eq!(reported(&output, "S6"), "123", "{}", case.shell);

    drop(sandbox);
}

#[test]
fn bash_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Bash,
        term: "dumb",
        bin: "bash",
        args: |_| vec!["--norc".into(), "-i".into()],
        extension: "sh",
        evaluate: Some(|path| format!("source {path}")),
        deactivate_call: "_starbase_deactivate",
        activates_on_prompt: true,
        defers_statements: false,
    });
}

#[test]
fn zsh_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Zsh,
        term: "dumb",
        bin: "zsh",
        args: |_| vec!["-f".into(), "-i".into()],
        extension: "zsh",
        evaluate: Some(|path| format!("source {path}")),
        deactivate_call: "_starbase_deactivate",
        activates_on_prompt: true,
        defers_statements: false,
    });
}

#[test]
fn fish_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Fish,
        term: "dumb",
        bin: "fish",
        args: |_| vec!["--no-config".into(), "-i".into()],
        extension: "fish",
        evaluate: Some(|path| format!("source {path}")),
        deactivate_call: "_starbase_deactivate",
        activates_on_prompt: true,
        defers_statements: false,
    });
}

#[test]
fn elvish_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Elvish,
        term: "dumb",
        bin: "elvish",
        args: |_| vec!["-norc".into()],
        extension: "elv",
        // `eval` is how the docs tell consumers to source it, and the reason
        // the hook has to export its functions with `edit:add-vars`
        evaluate: Some(|path| format!("eval (slurp < {path})")),
        deactivate_call: "_starbase_deactivate",
        activates_on_prompt: true,
        defers_statements: false,
    });
}

#[test]
fn xonsh_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Xonsh,
        term: "xterm-256color",
        bin: "xonsh",
        args: |_| vec!["--no-rc".into(), "-i".into()],
        extension: "xsh",
        // `execx` does not evaluate into the shell namespace, so this only
        // reaches `_starbase_deactivate` because the hook exports it
        evaluate: Some(|path| format!("execx($(cat {path}))")),
        deactivate_call: "_starbase_deactivate()",
        activates_on_prompt: true,
        defers_statements: false,
    });
}

#[test]
fn nu_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Nu,
        term: "dumb",
        bin: "nu",
        args: |_| vec!["--no-config-file".into()],
        extension: "nu",
        evaluate: Some(|path| format!("source \"{path}\"")),
        deactivate_call: "_starbase_deactivate",
        activates_on_prompt: true,
        defers_statements: true,
    });
}

// Murex is the one shell this harness cannot drive. Its line editor swallows
// the first Enter of a session and then appends anything typed after it to the
// line it is still holding, so a step either never runs or runs with the next
// step's text glued to its arguments. Disabling hints and the autocomplete
// timeouts gets as far as a correct activation (`S1 foo=123`) before the next
// step is mangled. The non-interactive suite still covers murex, and the
// `onPrompt` registration is covered by its snapshot.
#[test]
#[ignore = "murex's line editor cannot be driven through a pty, see the comment above"]
fn murex_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Murex,
        term: "xterm-256color",
        bin: "murex",
        // Murex's line editor treats a typed multi-line command as a paste and
        // asks about it, so the hook is loaded at startup, as a profile would
        args: |root| {
            vec![
                "-quiet".into(),
                "-c".into(),
                format!(
                    "config set shell hint-text-enabled false; \
                     config set shell autocomplete-soft-timeout 0; \
                     config set shell autocomplete-hard-timeout 0; \
                     source {root}/hook.mx"
                ),
                "-i".into(),
            ]
        },
        extension: "mx",
        evaluate: None,
        deactivate_call: "_starbase_deactivate",
        activates_on_prompt: true,
        defers_statements: false,
    });
}

#[test]
fn sh_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Sh,
        term: "dumb",
        bin: "sh",
        args: |_| vec!["-i".into()],
        extension: "sh",
        evaluate: Some(|path| format!(". {path}")),
        deactivate_call: "_starbase_deactivate",
        // POSIX shells shadow `cd` and have no prompt hook
        activates_on_prompt: false,
        defers_statements: false,
    });
}

#[test]
fn dash_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Dash,
        term: "dumb",
        bin: "dash",
        args: |_| vec!["-i".into()],
        extension: "sh",
        evaluate: Some(|path| format!(". {path}")),
        deactivate_call: "_starbase_deactivate",
        activates_on_prompt: false,
        defers_statements: false,
    });
}

#[test]
fn ash_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Ash,
        term: "dumb",
        bin: "ash",
        args: |_| vec!["-i".into()],
        extension: "sh",
        evaluate: Some(|path| format!(". {path}")),
        deactivate_call: "_starbase_deactivate",
        activates_on_prompt: false,
        defers_statements: false,
    });
}

#[test]
fn pwsh_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::Pwsh,
        term: "dumb",
        bin: "pwsh",
        args: |_| vec!["-NoProfile".into(), "-NoLogo".into()],
        extension: "ps1",
        evaluate: Some(|path| format!(". {path}")),
        deactivate_call: "_starbase_deactivate",
        activates_on_prompt: true,
        defers_statements: false,
    });
}

#[test]
fn powershell_activates_and_deactivates() {
    run_case(Case {
        shell: ShellType::PowerShell,
        term: "dumb",
        bin: "powershell",
        args: |_| vec!["-NoProfile".into(), "-NoLogo".into()],
        extension: "ps1",
        evaluate: Some(|path| format!(". {path}")),
        deactivate_call: "_starbase_deactivate",
        activates_on_prompt: true,
        defers_statements: false,
    });
}

// The default statement form targets a profile, which elvish evaluates in the
// interactive namespace, so a plain `fn` is enough there. Nothing outside a
// pty can tell the two forms apart.
#[test]
fn elvish_defines_profile_aliases() {
    let shell = ShellType::Elvish.build();
    let sandbox = create_empty_sandbox();
    let root = sandbox.path().display().to_string();

    sandbox.create_file(
        "report.sh",
        "printf '%s foo=%s\\n' \"$1\" \"${E2E_FOO:-unset}\"\n",
    );
    sandbox.create_file(
        "rc.elv",
        format!(
            "{}\necho rc-loaded\n",
            shell.format_alias_set("e2e_alias", &format!("sh {root}/report.sh"))
        ),
    );

    let Some(mut session) =
        Pty::spawn_with_term("elvish", &["-rc", &format!("{root}/rc.elv")], "dumb")
    else {
        return;
    };

    let output = session.sync("e2e_alias ALIAS", "ALIAS foo=");

    assert_eq!(reported(&output, "ALIAS"), "unset");

    session.send(&shell.format_alias_unset("e2e_alias"));
    session.send("e2e_alias GONE");

    let output = session.sync(&format!("sh {root}/report.sh AFTER"), "AFTER foo=");

    assert!(
        output.contains("executable file not found"),
        "alias outlived its removal:\n{output}"
    );

    drop(sandbox);
}

// Elvish aliases are a function added to the interactive namespace with
// `edit:add-vars`, so nothing about them is observable outside a pty.
#[test]
fn elvish_sets_and_unsets_aliases() {
    let shell = ShellType::Elvish.build();
    let sandbox = create_empty_sandbox();
    let root = sandbox.path().display().to_string();

    sandbox.create_file(
        "report.sh",
        "printf '%s foo=%s\\n' \"$1\" \"${E2E_FOO:-unset}\"\n",
    );
    sandbox.create_file(
        "set.elv",
        format!(
            "{}\n",
            shell.format(Statement::SetAlias {
                name: "e2e_alias",
                value: &format!("sh {root}/report.sh"),
                hook: true,
            })
        ),
    );
    sandbox.create_file(
        "unset.elv",
        format!(
            "{}\n{}\n",
            shell.format(Statement::UnsetAlias {
                name: "e2e_alias",
                hook: true,
            }),
            // A name that was never added must not abort the block
            shell.format(Statement::UnsetAlias {
                name: "e2e_never_added",
                hook: true,
            })
        ),
    );

    let Some(mut session) = Pty::spawn("elvish", &["-norc"]) else {
        return;
    };

    session.send(&format!("eval (slurp < {root}/set.elv)"));

    // The argument is forwarded, which a bare `fn` would reject
    let output = session.run("e2e_alias ALIAS", "ALIAS foo=");

    assert_eq!(reported(&output, "ALIAS"), "unset");

    session.send(&format!("eval (slurp < {root}/unset.elv)"));
    session.send("e2e_alias GONE");

    let output = session.run(&format!("sh {root}/report.sh AFTER"), "AFTER foo=");

    assert!(
        output.contains("executable file not found"),
        "alias outlived its removal:\n{output}"
    );

    drop(sandbox);
}
